mytest/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

admin.site.site_header = "LigaBot - Панель администратора"
admin.site.site_title = "LigaBot - Панель администратора"
admin.site.index_title = "Администрирование сайта"
urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', include('telegrambot.urls')),
    path('instructions/', include('django.contrib.flatpages.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

telegrambot/urls.py
from django.urls import path

from . import views, bot

urlpatterns = [
    path('settings', views.settings, name='settings'),
    path('apply-settings', views.apply_settings, name='apply-settings'),
    path('instruction', views.instruction, name='instruction'),
    path('instruction/prepare', views.instruction_prepare, name='instrucion_prepare'),
    path('logs', views.logs_list, name='logs_list'),
    path('mailing/delete/<int:id>', views.delete_message, name='delete_mailing'),
    path('mailing', views.mailing, name='mailing'),
    path('logs/get_updates', views.get_updates, name='get_updates'),
    path('preparations', views.prepare_list, name='prepare_list'),
    path('preparations<int:id>', views.prepare_detail, name='prepare_detail'),
    path('teachers/<int:id>', views.teacher_detail, name='teacher_detail'),
    path('logs/<int:id>', views.log_detail, name='log_detail'),
    path('teachers', views.teachers_list, name='teachers_list'),
    path('lessons', views.lessons_list, name='lessons_list'),
    path('branches', views.branches_list, name='branches_list'),
    path('branches/<int:id>', views.branch_detail, name='branch_detail'),
    path('telegrambot/<bot_token>', bot.reception_update, name='recive_update'),
    path('search', views.search, name='search'),
    path('', views.dashboard, name='dashboard'),

    path('sorting/', views.history_of_sorting, name='history_of_sorting'),
    path('sorting/statistic/branches/', views.static_sorting_by_branch, name='static_sorting_by_branch'),
    path('sorting/statistic/teachers/', views.static_sorting_by_teacher, name='static_sorting_by_teacher'),

    path('logs/botlog', views.get_bot_log, name='bot_log'),
    path('logs/errors/', views.errors_list, name='errors_list'),
    path('logs/errors/<int:error_id>/', views.error_detail, name='error_log'),
    # URL для собраний
    path('utils/delete-image/', views.delete_image, name='delete_image'),

    path('photo_callback/<int:chat_id>/<path:path>', views.photo_callback, name='photo_callback'),
    path('order_callback/<str:order_token>/', views.order_callback, name='order_callback'),

    path('photos/', views.photo_list, name='photo_list'),

    path('reference/', views.reference, name='reference'),

    path('tasks/', views.tasks_list, name='tasks_list'),
    path('tasks/<int:task_id>', views.task_detail, name='task_detail'),

    path('profile/<user_token>/logs/', views.profile_logs, name='profile_logs'),
    path('profile/<user_token>/tasks/', views.profile_tasks, name='profile_tasks'),


    path('orders/', views.order_list, name='orders_list'),
    path('orders/archive/', views.order_list_archive, name='orders_list_archive'),
    path('orders/<int:order_id>/', views.order_detail, name='order_detail'),
    path('orders/<str:order_token>/', views.order_detail_token, name='order_detail_token'),
]

telegrambot/models.py
import os
import secrets
import shutil
from datetime import datetime

from django.conf import settings
from django.contrib.postgres import fields
from django.contrib.postgres.fields import JSONField
from django.db import models
from django.shortcuts import reverse
from django.utils import timezone

from . import utils


class Departament(models.Model):
    """Модель отделов"""
    name = models.CharField(max_length=64, verbose_name='Название')
    only_office = models.BooleanField(verbose_name='Только для офиса', default=False)

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = 'Отделы'

    def __str__(self):
        return self.name


class Role(models.Model):
    """Модель роли"""
    name = models.CharField(max_length=64, verbose_name='Название')
    departament = models.ForeignKey(Departament, verbose_name='Отдел', on_delete=models.PROTECT, null=True, blank=True)
    danger_notification = models.BooleanField(verbose_name='Оповещение тревожной кнопкой', default=False)

    class Meta:
        verbose_name = 'Должность'
        verbose_name_plural = 'Должности'

    def __str__(self):
        return self.name


class Teacher(models.Model):
    """Модель преподавателя"""
    full_name = models.CharField(max_length=150, db_index=True, verbose_name='ФИО', unique=True)
    slug_name = models.CharField(max_length=150, null=True, blank=True)
    chat_id = models.IntegerField(null=True, default=0)  # chat_id в телеграмме
    status = models.IntegerField(null=True, default=0, verbose_name='Статус')   # Статус в системе
    password = models.CharField(max_length=128, null=True, blank=True, verbose_name='Токен')  # Пароль в системе
    additional = models.IntegerField(verbose_name='Дополнительное поле', default=0)
    is_active = models.BooleanField(verbose_name='Активный', default=True)
    roles = models.ManyToManyField(Role, blank=True, verbose_name='Роли')
    office = models.BooleanField(verbose_name='Офисный сотрудник', default=False)
    teacher = models.BooleanField(verbose_name='Преподаватель', default=True)

    def save(self, *args, **kwargs):
        if not self.slug_name:
            self.slug_name = utils.slug(self.full_name)
        if not self.password:
            self.password = secrets.token_urlsafe(64)
        super(Teacher, self).save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.full_name)

    def get_absolute_url(self):
        return reverse('teacher_detail', kwargs={'id': self.id})

    @property
    def get_short_name(self):
        full_name = self.full_name.split(' ')
        last_name = full_name[0]
        initial_1 = full_name[1][0] + '.' if len(full_name) >= 2 else ''
        initial_2 = full_name[2][0] + '.' if len(full_name) >= 3 else ''

        return '{} {} {}'.format(
            last_name,
            initial_1,
            initial_2)

    class Meta:
        ordering = ['-is_active', "full_name"]
        verbose_name = 'Пользователь бота'
        verbose_name_plural = 'Пользователи бота'


class NewUser(models.Model):
    """Модель незарегистрированного пользователя"""
    chat_id = models.IntegerField()
    status = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Неавторизованный пользователь'
        verbose_name_plural = 'Неавторизованые пользователи'


class Lesson(models.Model):
    DAY_OF_WEAK = (
        (1, 'ПН'),
        (2, 'ВТ'),
        (3, 'СР'),
        (4, 'ЧТ'),
        (5, 'ПТ'),
        (6, 'СБ'),
        (7, 'ВС'),
    )

    """Модель занятия"""
    name = models.CharField(verbose_name='Название', max_length=100, db_index=True)
    start = models.TimeField(verbose_name='Начало занятия')
    end = models.TimeField(verbose_name='Конец занятия')
    day_of_weak = models.IntegerField(
        verbose_name='День недели',
        choices=DAY_OF_WEAK
    )

    def __str__(self):
        return '{} - {}({}-{})'.format(
            self.get_day_of_weak_display(),
            self.name,
            self.start.strftime('%H:%M'),
            self.end.strftime('%H:%M'))

    class Meta:
        ordering = ['day_of_weak', 'start']
        verbose_name = 'Занятие'
        verbose_name_plural = 'Занятия'


class Branch(models.Model):
    """Модель филиала"""
    name = models.CharField(max_length=256, db_index=True)
    slug_name = models.CharField(max_length=256, blank=True)
    lessons = models.ManyToManyField(Lesson, verbose_name='Занятия', blank=True)
    is_active = models.BooleanField(default=True, verbose_name='Действующий')
    num_code = models.IntegerField(default=0, verbose_name='Код филиала')

    def save(self, *args, **kwargs):
        self.slug_name = utils.slug(self.name)
        # Создание папки филиала
        path = os.path.join(
            settings.BASE_DIR,
            settings.STATIC_DIRS,
            settings.IMAGE_DIR,
            self.slug_name
        )
        try:
            os.mkdir(path)
        except OSError:
            pass
        super(Branch, self).save(*args, **kwargs)

    # Вывод списка занятий
    def get_lessons(self):
        lessons_list = self.lessons.all()
        lessons_str = ''
        for lesson in lessons_list:
            lessons_str += ', ' + lesson.__str__()
        return lessons_str.lstrip(', ')

    get_lessons.short_description = 'Занятия'

    def __str__(self):
        return '{}'.format(self.name)

    def get_absolute_url(self):
        return reverse('branch_detail', kwargs={'id': self.id})

    @property
    def get_count_log(self):
        return LogSending.objects.filter(
            date=datetime.now(),
            branch=self
        ).count()

    @property
    def is_have_logs(self):
        count = LogSending.objects.filter(date=timezone.localtime(timezone.now()), branch=self).count()

        if count:
            return True
        else:
            return False

    @property
    def get_logs(self):
        logs = LogSending.objects.filter(date=timezone.localtime(timezone.now()), branch=self)
        return logs

    class Meta:
        ordering = ['-is_active', 'name']
        verbose_name = 'Филиал'
        verbose_name_plural = 'Филиалы'


day = ['ПН', 'ВТ', 'СР', 'ЧТ', 'ПТ', 'СБ', 'ВС']


class LogSending(models.Model):
    """Модель для ведения логов отправки фото"""
    date = models.DateField(verbose_name='Дата')
    time = models.TimeField(verbose_name='Время прибытия')
    time_before = models.IntegerField(verbose_name='Время до начала занятия', null=True, blank=True)
    teacher = models.ForeignKey(Teacher, on_delete=models.SET_NULL, verbose_name='Преподаватель', null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, null=True, verbose_name='Филиал')
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, verbose_name='Занятие', blank=True, null=True)
    photos = models.TextField(null=True, default='None', verbose_name='Местоположение фото')
    # end_time = models.TimeField(verbose_name='Время ухода', null=True)

    def get_absolute_url(self):
        return reverse('log_detail', kwargs={'id': self.id})

    @property
    def is_today(self):
        return timezone.localtime(timezone.now()).today() == self.date

    def save(self, *args, **kwargs):
        if self.lesson:
            self.time_before = (self.lesson.start.hour - self.time.hour) * 60 \
                               + int(self.lesson.start.minute - self.time.minute)
        super(LogSending, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        path = os.path.join(settings.BASE_DIR, self.photos)
        shutil.rmtree(path, ignore_errors=True)
        super(LogSending, self).delete(*args, **kwargs)

    class Meta:
        ordering = ['-id']
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'


class Preparation(models.Model):
    """Модель для подготовки"""
    date = models.DateField(verbose_name='Дата')
    time = models.TimeField(verbose_name='Время')
    photos = models.TextField(max_length=100, verbose_name='Местоположение фото')
    teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT, verbose_name='Преподаватель')

    def __str__(self):
        return "Подготовка {} {}".format(self.teacher, self.date)

    class Meta:
        ordering = ['-date']  # по умолчанию сортировка по дате
        verbose_name = 'Подготовка'
        verbose_name_plural = 'Подготовки'


class TempData(models.Model):
    """Модель для хранения временных данных"""
    date = models.DateField(verbose_name='Дата')
    time = models.TimeField(verbose_name='Время')
    teacher = models.ForeignKey(Teacher, on_delete=models.PROTECT, verbose_name='Преподаватель')
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Филиал')
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Занятие')
    counter = models.IntegerField(blank=True, null=True, default=0, verbose_name='Счетчик')

    def __str__(self):
        return "{} {} {} {}".format(self.id, self.teacher, self.date, self.time.strftime('%H:%M'))

    def delete(self, *args, **kwargs):
        path = os.path.join(settings.BASE_DIR, settings.MEDIA_DIR,
                            settings.TEMP_DIR, self.teacher.slug_name)
        shutil.rmtree(path, ignore_errors=True)
        self.teacher.status = 0
        self.teacher.save()
        super(TempData, self).delete(*args, **kwargs)

    class Meta:
        ordering = ['-date']
        verbose_name = 'Временная запись'
        verbose_name_plural = 'Временные записи'


class Message(models.Model):
    title = models.CharField(max_length=40, verbose_name='Заголовок', blank=True, null=True)
    body = models.TextField(verbose_name='Текст')
    datetime = models.DateTimeField(auto_created=True)
    receivers = models.TextField(verbose_name='Получатели')
    detail = models.TextField(verbose_name='Информация об отправленных сообщений', blank=True, null=True)

telegrambot/templates/telegrambot/base.html
<!DOCTYPE html>
<html lang="ru" dir="ltr">
<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="shortcut icon" href="{% static 'icon.png' %}" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="{% static 'picker/jquery.datetimepicker.css' %}">
    <script src="{% static 'picker/jquery.js' %}"></script>
    <script src="{% static 'picker/build/jquery.datetimepicker.full.min.js' %}"></script>
    <script src="{% static 'airpicker/js/datepicker.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'airpicker/css/datepicker.min.css' %}">
    <script src="{% static 'scripts.js' %}"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'multiple/css/multi-select.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <title>{% block title %}Заголовок не установлен{% endblock %}</title>
    {% block links %} {% endblock %}
</head>
<body style="opacity: 0">
{% block body_start %} {% endblock %}
<div class="b-popup">
    <span class="b-popup-close">&times</span>
    <div class="b-popup-content d-flex justify-content-between">
        <div id="prev-img" class="pop-btn  noselect"><img class="img-btn" src="/static/icons/prev-btn.png" alt=""></div>
        <div class="img-container">

            <img src="" id="b-popup-img" alt="">
        </div>
        <div id="next-img" class="pop-btn noselect"><img class="img-btn" src="/static/icons/next-btn.png" alt=""></div>
    </div>
</div>

<div id="alert-area">
</div>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'dashboard' %}">
        <img src="{% static 'icon.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        LigaBOT
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'dashboard' %}">Главная <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown_logs" role="button"
                   data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Отчёты
                    {% if count_sort_notification %}
                        <span class="badge badge-primary">{{ count_sort_notification }}</span>
                    {% endif %}
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown_logs">
                    <a class="dropdown-item" href="{% url 'logs_list' %}">Кабинеты<span
                            class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{% url 'prepare_list' %}">Подготовки<span
                            class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{% url 'history_of_sorting' %}">Сортировки
                        {% if count_sort_notification %}
                            <span class="badge badge-primary">
                        {{ count_sort_notification }}
                                                </span>
                        {% endif %}<span
                                class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{% url 'photo_list' %}">Фото с занятий<span
                            class="sr-only">(current)</span></a>
                </div>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                    Дополнительно
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'teachers_list' %}">Преподаватели<span class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{% url 'branches_list' %}">Филиалы<span
                            class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{% url 'lessons_list' %}">Занятия<span
                            class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{% url 'mailing' %}">Рассылка<span
                            class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{% url 'settings' %}">Настройки
                        <span class="sr-only">(current)</span></a>
                    <a class="dropdown-item" href="{% url 'orders_list' %}">Заказы деталей
                        <span class="sr-only">(current)</span></a>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'tasks_list' %}">Задачи<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/admin">Admin<span class="sr-only">(current)</span></a>
            </li>
        </ul>
        <ul class="navbar-nav ">
            <li class="nav-item search_block ">
                <input id="search" class="form-control mr-sm-3" type="search"
                       placeholder="Поиск..." aria-label="Search" name="search" autocomplete="off">
                <ul id="search_result" class="p-0 shadow-lg"></ul>
            </li>
        </ul>
    </div>
</nav>
<div class="container-fluid shadow-lg border py-3">
    {% block content %}
        Контент остутсвтвует
    {% endblock %}
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="/static/bootstrap/js/bootstrap.min.js"></script>
<script src="{% static 'multiple/js/jquery.multi-select.js' %}"></script>
<script src="{% static 'jquery.quicksearch.js' %}"></script>
<script>
    $(document).ready(function () {
        $('body').animate({opacity: '1'}, 100)
    });
</script>
</body>
</html>

telegrambot/templates/telegrambot/branch_detail.html
{% extends 'telegrambot/base.html' %}


{% block title %}
    {{branch.name}} - Обзор
{% endblock %}

{% block content %}
        <h3 class="text-center mt-2">{{ branch.name }} ID: {{branch.id}}</h3>


        <div class="row">
            <h5 class="col-12 text-center">Последние логи</h5>
        </div>
<div class="table-responsive">
        <table class="table table-bordered table-light table-hover table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Дата</th>
                <th scope="col">Время</th>
                <th scope="col">Время до занятия</th>
                <th scope="col">Преподаватель </th>
                <th scope="col">Занятие</th>
                <th scope="col">Функции</th>
              </tr>
            </thead>
            <tbody>
                {% for log in page.object_list %}
                    <tr>
                        <th scope="row">{{ log.id}}</th>
                        <th>{{ log.date|date:"d.m.Y" }}</th>
                        <th>{{ log.time|date:"H:i" }}</th>
                        {% load pluralize %}
                        <th>{% if log.time_before %}{{ log.time_before}} {{ log.time_before|pluralize:"минута,минуты,минут"}} {% else %} - {% endif %}</th>
                        <th><a href="{{ log.teacher.get_absolute_url}}">{{ log.teacher}}</a></th>
                        <th>{% if log.lesson %}{{ log.lesson}} {% else %} - {% endif %}</th>
                        <th><a href="{{ log.get_absolute_url }}">Подробнее</a></th>
                    </tr>

                {% endfor %}
            </tbody>
        </table>
{%  if page.has_other_pages %}
    {% load bootstrap_pagination %}
    {% bootstrap_paginate page range=5 show_first_last=True%}
{% endif %}
</div>
{% endblock %}

telegrambot/templates/telegrambot/errors_list.html
{% extends 'telegrambot/base.html' %}

{% block title %}
Список ошибок
{% endblock %}

{% block content %}
    <div class="row">
    {% for error in errors %}
    <div class="col-11 mx-auto my-2 p-2 text-center border">
        <a href="{% url 'error_log' error.id %}">Ошибка №{{ error.id }}</a>
    </div>
    {% endfor %}
    </div>
{% endblock %}

telegrambot/templates/telegrambot/lessons.html
{% extends 'telegrambot/base.html' %}


{% block title %}
    Список занятий
{% endblock %}

{% block content %}
        <div class="row">
            <h1 class="col-12 text-center">Занятия</h1>
        </div>
        <table class="table table-bordered table-sm">
            <thead class="thead-dark">
              <tr>
                <th scope="col">ID</th>
                <th scope="col">Название</th>
                <th scope="col">День недели</th>
                <th scope="col">Время</th>
              </tr>
            </thead>
            <tbody>
                {% for lesson in lessons %}
                    <tr>
                        <th scope='row'>{{ lesson.id}}</th>
                        <th>{{ lesson.name }}</th>
                        <th>{{ lesson.get_day_of_weak_display}}</th>
                        <th>{{ lesson.start }} - {{ lesson.end }}</th>
                    </tr>

                {% endfor%}
            </tbody>
        </table>
{% endblock %}

telegrambot/templates/telegrambot/prepare_list.html
{% extends 'telegrambot/base.html' %}

{% block title %}
    Подготовка
{% endblock %}

{% block content %}
    {% load bootstrap_pagination %}
    <div class="row">
        <h3 class="col-12 text-center">Подготовки {{ date.start }} - {{ date.end }}</h3>
    </div>

    <div class="row">
        <form action="" method="GET" class="col-12 col-md-6 row d-flex justify-content-center">
            <div class="form-row col-12 col-md-6">
                <label for="id_date" class="col-3 col-form-label col-form-label-sm">{{ form.date.label }} </label>
                <input id="id_date" class="col-9 mb-3 form-control form-control-sm" name="date"
                       type="text" placeholder="{% now 'd.m.Y' %}" autocomplete="off"
                       value='{% if form.date.value %}{{ form.date.value }}{% endif %}'>
                {{ form.date.errors }}
            </div>
            <div class="col-12 col-md-6">
                <button type="submit" name="button" class="btn btn-primary btn-sm btn-block">Применить</button>
            </div>
        </form>
        <div class="col-md-6 col-12">
        </div>
    </div>
    <a href="?date={{ date.prev_weak }}">Предыдущая неделя</a>
    {% if date.now_weak %}
        <a href="?date={{ date.now_weak }}">Текущая неделя</a>
    {% endif %}
    {% if date.next_weak %}
        <a href="?date={{ date.next_weak }}">Следующая неделя</a>
    {% endif %}

    <!-- PAGINATOR !-->
    <div class="row d-flex justify-content-center">
        {% bootstrap_paginate page range=5 %}
    </div>

    <div class="table-responsive">
        <table class="table table-sm table-borderless my-table p-2"
               style="border-spacing: 0 10px;border-collapse: separate">
            <thead>
            <tr>
                <th scope="col">Преподаватель</th>
                <th scope="col">Дата</th>
                <th scope="col">Время</th>
                <th scope="col">Фото</th>
            </tr>
            </thead>
            <tbody>
            {% for teacher, prepare in result.items %}
                {% if prepare != False %}
                    <tr class="table-success my-tr">
                        <th style="border-radius: 4px 0 0 4px">{{ prepare.0.teacher }}</th>
                        <th>{{ prepare.0.date|date:"d.m.Y" }}</th>
                        <th>{{ prepare.0.time|date:"H:i" }}</th>
                        <th class="text-left" style="border-radius: 0 4px 4px 0">{% for image in prepare.1 %}
                            <img src="/{{ image }}" alt="Not found" height="50" class="img-popup img-contextmenu"
                                 data-id="{{ prepare.2 }}" data-object="prepare">
                        {% endfor %}
                        </th>
                    </tr>
                {% else %}
                    <tr class="table-danger my-tr">
                        <th style="border-radius: 4px 0 0 4px" scope="row">{{ teacher }}</th>
                        <th scope="row"> -</th>
                        <th scope="row"> -</th>
                        <th scope="row" style="border-radius: 0 4px 4px 0"> -</th>
                    </tr>
                {% endif %}
            {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- PAGINATOR !-->
    <div class="row d-flex justify-content-center">
        {% bootstrap_paginate page range=5 %}
    </div>
    <script type="text/javascript">

        $('#id_date').datepicker({
            maxDate: new Date(),
            autoClose: true,
        });

    </script>
    <script src="/static/scripts/contextmenu.js"></script>
{% endblock %}

telegrambot/templates/telegrambot/show_meeting.html
{% extends 'telegrambot/base.html' %}

{% block title %}
    Собрание
{% endblock %}

{% block content %}
    {% for teacher in teachers %}
        {{ teacher }}
    {% endfor %}
{% endblock %}

telegrambot/templates/telegrambot/task_detail.html
{% extends 'telegrambot/base.html' %}

{% block title %}
    История задачи
{% endblock %}

{% block content %}
    <div class="row">
        <h4 class="col-12 text-center">История взаимодействия с задачей</h4>
    </div>

    <div class="row">
        <h5 class="text-center col-12">Суть задачи</h5>
        <p class="col-12 text-center">
            {{ task.text }}
        </p>
        <h5 class="col-12 text-center">Постановщик</h5>
        <p class="col-12 text-center">
            {{ task.director }}
        </p>
        <h5 class="col-12 text-center">Исполнитель</h5>
        <p class="col-12 text-center">
            {{ task.executor }}
        </p>

        <h5 class="col-12 text-center">История</h5>
        <div class="table-responsive">
            <table class="table table-sm table-borderless my-table p-2"
                   style="border-spacing: 0 10px;border-collapse: separate">
                <thead>
                <tr>
                    <th scope="col">Дата</th>
                    <th scope="col">Действие</th>
                </tr>
                </thead>
                <tbody>
                {% for record in task_history %}
                    <tr class="table-hover my-tr">
                        <th style="border-radius: 4px 0 0 4px" scope="row">{{ record.created|date:"d.m.Y" }}</th>
                        <th scope="row">{{ record.comment }}</th>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}